name: Deploy Prod Branch On Merge

on:
  push:
    branches: [ "prod" ]

permissions:
  id-token: write # OIDC 인증에 필요
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHubDeployment
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create Dockerrun.aws.json
        run: |
          echo "${{ secrets.PROD_DOCKER_RUN_AWS_JSON }}" > Dockerrun.aws.json

      - name: Deploy To Beanstalk
        run: |
          # 새 애플리케이션 버전 생성
          aws elasticbeanstalk create-application-version \
            --application-name ${{ secrets.EB_APPLICATION_NAME }} \
            --version-label "ver-${{ github.sha }}" \

          # 기존 환경 업데이트
          aws elasticbeanstalk update-environment \
            --environment-name ${{ secrets.EB_ENVIRONMENT_NAME }} \
            --version-label "ver-${{ github.sha }}"
          
          # 배포 상태 확인
          aws elasticbeanstalk wait environment-updated \
            --environment-name ${{ secrets.EB_ENVIRONMENT_NAME }}