name: Deploy on Merge

on:
  push:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # 서버에 통신하기 위한 SSH를 설정합니다.
      - name: Setup SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 배포 서버에 host 키 확인
            sudo mkdir -p ~/.ssh
            sudo ssh-keyscan ${{ secrets.DEV_SERVER_HOST }} >> ~/.ssh/known_hosts
            
            # 배포 서버에서 DockerHub Login
            sudo docker login -u ${{ secrets.DOCKERHUN_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            
            # Pull Docker Image
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/runninghi-dev:latest
            
            # Stop and Remove existing contrainer
            sudo docker stop runninghi-dev || true && docker rm runninghi-dev || true
            
            # Run new container
            sudo docker run -d --name runninghi-dev -p ${{ secrets.DEV_SERVER_PORT }}:8080 ${{ secrets.DOCKERHUB_USERNAME }}/runninghi-dev:latest